version: '2'
services:

    #
    # mender-client
    #
    mender-client:
        image: mendersoftware/mender-client-qemu:1.6.x
        networks:
            - mender
        stdin_open: true
        tty: true
        privileged: true
