#!/bin/bash
set -e

../verify-docker-versions

exec docker-compose \
     -p menderproduction \
     -f ../docker-compose.yml \
     -f ../docker-compose.storage.s3.yml \
     -f ./prod.yml \
     "$@"
